# Generated by Django 2.0.5 on 2018-06-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('coordinates', models.CharField(max_length=40)),
                ('extra_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocationMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('locations', models.ManyToManyField(to='sensor_network.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('measure_type', models.CharField(choices=[('S', 'Scalar'), ('B', 'Binary'), ('T', 'Text')], max_length=6)),
                ('measure', models.CharField(max_length=40)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_network.Location')),
            ],
        ),
        migrations.CreateModel(
            name='SensorNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='AtomicEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_network.Event')),
                ('measure_limit', models.CharField(max_length=25)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_network.Sensor')),
            ],
            bases=('sensor_network.event',),
        ),
        migrations.CreateModel(
            name='ComplexEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_network.Event')),
                ('events', models.ManyToManyField(related_name='complex_event_events', to='sensor_network.Event')),
            ],
            bases=('sensor_network.event',),
        ),
        migrations.AddField(
            model_name='sensornetwork',
            name='events',
            field=models.ManyToManyField(to='sensor_network.Event'),
        ),
        migrations.AddField(
            model_name='sensornetwork',
            name='sensors',
            field=models.ManyToManyField(to='sensor_network.Sensor'),
        ),
    ]
