# Generated by Django 2.0.5 on 2018-07-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexevent',
            name='function',
            field=models.CharField(choices=[('seq', 'seq'), ('seq_any', 'seq_any'), ('overlaps', 'overlaps'), ('any', 'any')], default='seq', max_length=10),
        ),
    ]
