# Generated by Django 2.0.5 on 2018-08-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='action',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
