# Generated by Django 2.0.5 on 2018-07-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0002_auto_20180608_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='function',
            field=models.CharField(choices=[('less_than', 'less_than'), ('great_than', 'great_than'), ('less_than_equal', 'less_than_equal'), ('great_than_equal', 'great_than_equal'), ('not_less_than', 'not_less_than'), ('not_great_than', 'not_great_than'), ('not_less_than_equal', 'not_less_than_equal'), ('not_great_than_equal', 'not_great_than_equal'), ('equal', 'equal'), ('not_equal', 'not_equal')], default='less_than', max_length=25),
        ),
    ]
