# Generated by Django 2.0.5 on 2018-08-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0002_auto_20180725_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atomicevent',
            name='sensors',
        ),
    ]
