# Generated by Django 2.0.5 on 2018-06-20 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0002_auto_20180608_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='extra_info',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='locationmap',
            name='locations',
            field=models.ManyToManyField(blank=True, to='sensor_network.Location'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sensor_network.Location'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='measure_type',
            field=models.CharField(choices=[('S', 'Scalar'), ('B', 'Binary'), ('T', 'Text'), ('M', 'Misc Data')], max_length=6),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='measures',
            field=models.ManyToManyField(blank=True, to='sensor_network.Measure'),
        ),
        migrations.AlterField(
            model_name='sensornetwork',
            name='events',
            field=models.ManyToManyField(blank=True, to='sensor_network.Event'),
        ),
        migrations.AlterField(
            model_name='sensornetwork',
            name='sensors',
            field=models.ManyToManyField(blank=True, to='sensor_network.Sensor'),
        ),
    ]
