# Generated by Django 2.0.5 on 2018-06-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0003_auto_20180620_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='measure_type',
            field=models.CharField(choices=[('S', 'Scalar'), ('B', 'Binary'), ('T', 'Text'), ('M', 'Misc')], max_length=6),
        ),
    ]
