# Generated by Django 2.0.5 on 2018-07-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0003_event_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomicevent',
            name='measure_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
