# Generated by Django 2.0.5 on 2018-09-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0002_event_action'),
        ('sensor_network', '0003_remove_atomicevent_sensors'),
    ]

    operations = [
    ]
