# Generated by Django 2.0.5 on 2018-09-18 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0004_merge_20180915_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('iri', models.CharField(max_length=50)),
                ('function', models.CharField(choices=[('true', 'true')], default='true', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='action',
        ),
        migrations.RemoveField(
            model_name='location',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='location',
            name='point_1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='location',
            name='point_2',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='location',
            name='point_3',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='location',
            name='point_4',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='eventaction',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor_network.Event'),
        ),
    ]
