# Generated by Django 2.0.5 on 2018-07-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0004_auto_20180705_2042'),
        ('sensor_network', '0004_auto_20180620_0142'),
    ]

    operations = [
    ]
