# Generated by Django 2.0.5 on 2018-07-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0006_auto_20180717_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='iri',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
