# Generated by Django 2.0.5 on 2018-07-17 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0007_auto_20180717_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='measures',
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
        migrations.AddField(
            model_name='measurelog',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_log', to='sensor_network.Sensor'),
        ),
    ]
