# Generated by Django 2.0.5 on 2018-07-19 13:43

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0008_auto_20180717_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complexevent',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_complex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_end',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
