# Generated by Django 2.0.5 on 2018-07-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0009_auto_20180719_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='function',
        ),
        migrations.AddField(
            model_name='atomicevent',
            name='function',
            field=models.CharField(choices=[('less_than', 'less_than'), ('great_than', 'great_than'), ('less_than_equal', 'less_than_equal'), ('great_than_equal', 'great_than_equal'), ('not_less_than', 'not_less_than'), ('not_great_than', 'not_great_than'), ('not_less_than_equal', 'not_less_than_equal'), ('not_great_than_equal', 'not_great_than_equal'), ('equal', 'equal'), ('not_equal', 'not_equal')], default='less_than', max_length=25),
        ),
        migrations.AddField(
            model_name='complexevent',
            name='first_event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='first_ev', to='sensor_network.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complexevent',
            name='function',
            field=models.CharField(choices=[('Seq', 'Seq'), ('Overlaps', 'Overlaps')], default='Seq', max_length=10),
        ),
        migrations.AddField(
            model_name='complexevent',
            name='second_event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='second_ev', to='sensor_network.Event'),
            preserve_default=False,
        ),
    ]
