# Generated by Django 2.0.5 on 2018-07-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0010_auto_20180719_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexevent',
            name='function',
            field=models.CharField(choices=[('Seq', 'Seq'), ('Overlaps', 'Overlaps'), ('Both', 'Both')], default='Seq', max_length=10),
        ),
    ]
