# Generated by Django 2.0.5 on 2018-07-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0011_auto_20180719_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveableSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_network.Sensor')),
            ],
            bases=('sensor_network.sensor',),
        ),
        migrations.CreateModel(
            name='MultimediaSensor',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensor_network.Sensor')),
            ],
            bases=('sensor_network.sensor',),
        ),
        migrations.AddField(
            model_name='sensor',
            name='is_moveable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='is_multimedia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensornetwork',
            name='location_map',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='sensor_network.LocationMap'),
            preserve_default=False,
        ),
    ]
