# Generated by Django 2.0.5 on 2018-07-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0013_auto_20180719_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensornetwork',
            name='location_map',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sensor_network.LocationMap'),
        ),
    ]
