# Generated by Django 2.0.5 on 2018-07-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0014_auto_20180719_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor_network.Location'),
        ),
    ]
