# Generated by Django 2.0.5 on 2018-07-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0016_auto_20180719_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveablesensor',
            name='sensor_ptr',
        ),
        migrations.DeleteModel(
            name='MoveableSensor',
        ),
    ]
