# Generated by Django 2.0.5 on 2018-07-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0017_auto_20180722_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='coordinates',
        ),
    ]
