# Generated by Django 2.0.5 on 2018-07-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_network', '0018_remove_location_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='coordinates',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
