# Generated by Django 2.0.5 on 2018-08-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('uri', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OntoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded_graph', models.BooleanField(default=False)),
                ('loaded_ontologies', models.IntegerField(default=0)),
                ('loaded_namespaces', models.IntegerField(default=0)),
                ('namespaces', models.ManyToManyField(blank=True, related_name='ontology_namespaces', to='rdf_manager.NameSpace')),
                ('ontology_files', models.ManyToManyField(blank=True, to='rdf_manager.OntoFile')),
            ],
            options={
                'verbose_name_plural': 'Ontologies',
            },
        ),
        migrations.AlterUniqueTogether(
            name='namespace',
            unique_together={('name', 'uri')},
        ),
    ]
