# Generated by Django 2.0.5 on 2018-05-31 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('uri', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OntoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('namespace_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rdf_manager.NameSpace')),
                ('namespaces', models.ManyToManyField(related_name='ontology_namespaces', to='rdf_manager.NameSpace')),
                ('ontology_files', models.ManyToManyField(to='rdf_manager.OntoFile')),
            ],
            bases=('rdf_manager.namespace',),
        ),
    ]
