# Generated by Django 2.0.5 on 2018-05-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdf_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontology',
            name='namespaces',
            field=models.ManyToManyField(blank=True, related_name='ontology_namespaces', to='rdf_manager.NameSpace'),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='ontology_files',
            field=models.ManyToManyField(blank=True, to='rdf_manager.OntoFile'),
        ),
    ]
