# Generated by Django 2.0.5 on 2018-09-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdf_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ontology',
            name='ontology_files',
            field=models.ManyToManyField(to='rdf_manager.OntoFile'),
        ),
    ]
