# Generated by Django 2.0.5 on 2018-05-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdf_manager', '0002_auto_20180531_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ontology',
            options={'verbose_name_plural': 'Ontologies'},
        ),
    ]
