# Generated by Django 2.0.5 on 2018-05-31 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdf_manager', '0003_auto_20180531_1835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='namespace',
            unique_together={('name', 'uri')},
        ),
    ]
